let TIME_SHEET_FIRBASE_API_KEY = null;
let TIME_SHEET_FIRBASE_AUTH_DOMAIN = null;
let TIME_SHEET_FIRBASE_PROJECT_ID = null;
let TIME_SHEET_FIRBASE_STORAGE_BUCKET = null;
let TIME_SHEET_FIRBASE_MESSAGING_SENDER_ID = null;
let TIME_SHEET_FIRBASE_APP_ID = null;
let TIME_SHEET_FIRBASE_MEASUREMENT_ID = null;

if (process.env.REACT_APP_ENVIRONMENT.includes("production")){
    TIME_SHEET_FIRBASE_API_KEY = process.env.REACT_APP_PRODUCTION_API_KEY;
    TIME_SHEET_FIRBASE_AUTH_DOMAIN = process.env.REACT_APP_PRODUCTION_AUTH_DOMAIN;
    TIME_SHEET_FIRBASE_PROJECT_ID = process.env.REACT_APP_PRODUCTION_PROJECT_ID;
    TIME_SHEET_FIRBASE_STORAGE_BUCKET = process.env.REACT_PRODUCTION_APP_STORAGE_BUCKET;
    TIME_SHEET_FIRBASE_MESSAGING_SENDER_ID = process.env.REACT_APP_PRODUCTION_MESSAGING_SENDER_ID;
    TIME_SHEET_FIRBASE_APP_ID = process.env.REACT_APP_PRODUCTION_APP_ID;
    TIME_SHEET_FIRBASE_MEASUREMENT_ID = process.env.REACT_APP_PRODUCTION_MEASUREMENT_ID;
}else if (process.env.REACT_APP_ENVIRONMENT.includes("development")){
    TIME_SHEET_FIRBASE_API_KEY = process.env.REACT_APP_DEV_API_KEY;
    TIME_SHEET_FIRBASE_AUTH_DOMAIN = process.env.REACT_APP_DEV_AUTH_DOMAIN;
    TIME_SHEET_FIRBASE_PROJECT_ID = process.env.REACT_APP_DEV_PROJECT_ID;
    TIME_SHEET_FIRBASE_STORAGE_BUCKET = process.env.REACT_APP_DEV_STORAGE_BUCKET;
    TIME_SHEET_FIRBASE_MESSAGING_SENDER_ID = process.env.REACT_APP_DEV_MESSAGING_SENDER_ID;
    TIME_SHEET_FIRBASE_APP_ID = process.env.REACT_APP_DEV_APP_ID;
    TIME_SHEET_FIRBASE_MEASUREMENT_ID = process.env.REACT_APP_DEV_MEASUREMENT_ID;
}else{
    throw new Error("No environment was provided");
}

//encrypt and decrypt key for passwords
export const ENCRIPT_KEY = process.env.REACT_APP_ENCRIPT_SECRET;

//config for firebase and firestore
export const FB_API_KEY = TIME_SHEET_FIRBASE_API_KEY;
export const FB_AUTH_DOMAIN = TIME_SHEET_FIRBASE_AUTH_DOMAIN;
export const FB_PROJECT_ID = TIME_SHEET_FIRBASE_PROJECT_ID;
export const FB_STORAGE_BUCKET = TIME_SHEET_FIRBASE_STORAGE_BUCKET;
export const FB_MESSAGING_SENDER_ID = TIME_SHEET_FIRBASE_MESSAGING_SENDER_ID;
export const FB_APP_ID = TIME_SHEET_FIRBASE_APP_ID;
export const FB_MEASUREMENT_ID = TIME_SHEET_FIRBASE_MEASUREMENT_ID;